markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Sai Warang
url: http://zachholman.com
description: Jekyll blog is ninja
twitter: cyprusad
github: cyprusad
gravatar_url: http://gravatar.com/avatar/ecf559571ebd26f6600a5a1881090e1b
